# Notebook Contents

In this particular notebook, we will have a look at the different descripive statistical functions available in Pandas. 

##### <span style="color:green">1. DataFrame.count()</span>
##### <span style="color:green">2. DataFrame.min()</span> 
#####  <span style="color:green">3. DataFrame.max()</span>
##### <span style="color:green">4. DataFrame.mean()</span>
##### <span style="color:green">5. DataFrame.median</span>
##### <span style="color:green">6. DataFrame.mode()</span>
##### <span style="color:green">7. DataFrame.sum()</span>
##### <span style="color:green">8. DataFrame.diff()</span>
##### <span style="color:green">9. DataFrame.pct_change()</span>
##### <span style="color:green">10. DataFrame.var()</span>
##### <span style="color:green">11. DataFrame.std()</span>
##### <span style="color:green">12. DataFrame.rolling(window=).mean()</span>
##### <span style="color:green">13. DataFrame.expanding(min_periods=).mean()</span>
##### <span style="color:green">14. DataFrame.cov()</span>
##### <span style="color:green">15. DataFrame.cor()</span>
##### <span style="color:green">16. DataFrame.kur()</span>
##### <span style="color:green">17. DataFrame.skew()</span>

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline


df = pd.read_csv ('./CSV/GBPUSD.csv')
df.head()

,Local time,Open,High,Low,Close,Volume
0,28.02.2018 22:00:00.000 GMT-0000,1.37591,1.37846,1.37115,1.37746,2.096890e+08
1,01.03.2018 22:00:00.000 GMT-0000,1.37745,1.38166,1.37554,1.37980,1.913914e+08
2,02.03.2018 22:00:00.000 GMT-0000,1.37980,1.37980,1.37980,1.37980,0.000000e+00
3,03.03.2018 22:00:00.000 GMT-0000,1.37980,1.37980,1.37980,1.37980,0.000000e+00
4,04.03.2018 22:00:00.000 GMT-0000,1.37886,1.38769,1.37664,1.38482,1.853236e+08

### DataFrame.diff()

This method returns the 'difference' between the current observation and the previous observation.

### DataFrame.pct_change()

This method returns the percentage change of the current observation with the previous observation.

### DataFrame.var()
Variance

### DataFrame.std()
Standard deviation

### DataFrame.cov()
Covariance

### DataFrame.corr()
Correlation

### DataFrame.kurt()
Kurtosis

In [5]:
print('\n==================\n Diff Method \n==================\n', 
      df['Open'].diff().head())

print('\n==================\n Diff Method \n==================\n', 
      df['Close'].diff().head())

print('\n==================\n Diff Method \n==================\n', 
      df['Close'].diff().var().head())

print('\n==================\n Diff Method \n==================\n', 
      df['Close'].diff().std().head())

print('\n==================\n Diff Method \n==================\n', 
      df['Close'].diff().std())

==================
 Diff Method
==================
 0        NaN
1    0.00154
2    0.00235
3    0.00000
4   -0.00094
Name: Open, dtype: float64

==================
 Diff Method
==================
 0        NaN
1    0.00234
2    0.00000
3    0.00000
4    0.00502
Name: Close, dtype: float64

In this notebook, we will have a look at the different descriptive statistical functions available in Python. 

## Notebook Contents

##### <span style="color:green">1. Indexing using .loc()</span>
##### <span style="color:green">2. Indexing using .iloc()</span>
#####  <span style="color:green">3. Indexing using .ix()</span>
##### <span style="color:green">4. Missing Values</span>
##### <span style="color:green">5. DataFrame.isnull()</span>
##### <span style="color:green">6. DataFrame.notnull()</span>
##### <span style="color:green">7. DataFrame.fillna()</span>
##### <span style="color:green">8. DataFrame.dropna()</span>
##### <span style="color:green">9. Replacing values</span>
##### <span style="color:green">10. Reindexing</span>

## Indexing using .loc()

In [11]:
df.shape #How many rows and columns

df.loc[:,['Close', 'Open']] #Select only all rows of Close and Open 

df.loc[:4,['Close', 'Open']] #Select only the first 5 rows of Close and Open 

df.loc[:4] #Select only the first 5 rows of all the columns

,Local time,Open,High,Low,Close,Volume
0,28.02.2018 22:00:00.000 GMT-0000,1.37591,1.37846,1.37115,1.37746,2.096890e+08
1,01.03.2018 22:00:00.000 GMT-0000,1.37745,1.38166,1.37554,1.37980,1.913914e+08
2,02.03.2018 22:00:00.000 GMT-0000,1.37980,1.37980,1.37980,1.37980,0.000000e+00
3,03.03.2018 22:00:00.000 GMT-0000,1.37980,1.37980,1.37980,1.37980,0.000000e+00
4,04.03.2018 22:00:00.000 GMT-0000,1.37886,1.38769,1.37664,1.38482,1.853236e+08

## Indexing using .iloc()

Another way to perform indexing is using the 'iloc()' method.

iloc is extremely useful when your data is not labelled and you need to refer to columns using their integer location instead

In [17]:
df.iloc[:4] #Select the first 4 rows

df.iloc[:4, 1:3] # Select the first 4 rows and columns from 2 to 3

      Open     High
0  1.37591  1.37846
1  1.37745  1.38166
2  1.37980  1.37980
3  1.37980  1.37980

## Missing Values

Missing values are values that are absent from the data frame. Usually, all the data frames that you would work on, would be large and there will be a case of 'missing values' in most of them. <br>
<br>
Hence, it becomes important for you to learn how to handle these missing values.

In [18]:
df.isnull() #Returns boolean for null values for each data point

df['Close'].fillna(method='backfill') #Backfill any null values
df.fillna(method='ffill') #Forward fill for entire df

df.dropna() # By default, dropna() will exclude or drop all the rows which has even one NaN value in it

     Local time   Open   High    Low  Close  Volume
0         False  False  False  False  False   False
1         False  False  False  False  False   False
2         False  False  False  False  False   False
3         False  False  False  False  False   False
4         False  False  False  False  False   False
5         False  False  False  False  False   False
6         False  False  False  False  False   False
7         False  False  False  False  False   False
8         False  False  False  False  False   False
9         False  False  False  False  False   False
10        False  False  False  False  False   False
11        False  False  False  False  False   False
12        False  False  False  False  False   False
13        False  False  False  False  False   False
14        False  False  False  False  False   False
15        False  False  False  False  False   False
16        False  False  False  False  False   False
17        False  False  False  False  False   False
18        False  False  False  False  False   False
19        False  False  False  False  False   False
20        False  False  False  False  False   False
21        False  False  False  False  False   False
22        False  False  False  False  False   False
23        False  False  False  False  False   False
24        False  False  False  False  False   False
25        False  False  False  False  False   False
26        False  False  False  False  False   False
27        False  False  False  False  False   False
28        False  False  False  False  False   False
29        False  False  False  False  False   False
..          ...    ...    ...    ...    ...     ...
337       False  False  False  False  False   False
338       False  False  False  False  False   False
339       False  False  False  False  False   False
340       False  False  False  False  False   False
341       False  False  False  False  False   False
342       False  False  False  False  False   False
343       False  False  False  False  False   False
344       False  False  False  False  False   False
345       False  False  False  False  False   False
346       False  False  False  False  False   False
347       False  False  False  False  False   False
348       False  False  False  False  False   False
349       False  False  False  False  False   False
350       False  False  False  False  False   False
351       False  False  False  False  False   False
352       False  False  False  False  False   False
353       False  False  False  False  False   False
354       False  False  False  False  False   False
355       False  False  False  False  False   False
356       False  False  False  False  False   False
357       False  False  False  False  False   False
358       False  False  False  False  False   False
359       False  False  False  False  False   False
360       False  False  False  False  False   False
361       False  False  False  False  False   False
362       False  False  False  False  False   False
363       False  False  False  False  False   False
364       False  False  False  False  False   False
365       False  False  False  False  False   False
366       False  False  False  False  False   False

[367 rows x 6 columns]

In [22]:
df_reindexed = df.reindex(index = df['Local time'], columns = df['Open', 'High', 'Low','Close'])

KeyError: ('Open', 'High', 'Low', 'Close')

In [21]:
print(df_reindexed)

                                  Open  High  Low  Close
Local time
28.02.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
01.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
02.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
03.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
04.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
05.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
06.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
07.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
08.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
09.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
10.03.2018 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
11.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
12.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
13.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
14.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
15.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
16.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
17.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
18.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
19.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
20.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
21.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
22.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
23.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
24.03.2018 21:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
25.03.2018 22:00:00.000 GMT+0100   NaN   NaN  NaN    NaN
26.03.2018 22:00:00.000 GMT+0100   NaN   NaN  NaN    NaN
27.03.2018 22:00:00.000 GMT+0100   NaN   NaN  NaN    NaN
28.03.2018 22:00:00.000 GMT+0100   NaN   NaN  NaN    NaN
29.03.2018 22:00:00.000 GMT+0100   NaN   NaN  NaN    NaN
...                                ...   ...  ...    ...
31.01.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
01.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
02.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
03.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
04.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
05.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
06.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
07.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
08.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
09.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
10.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
11.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
12.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
13.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
14.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
15.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
16.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
17.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
18.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
19.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
20.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
21.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
22.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
23.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
24.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
25.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
26.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
27.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
28.02.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN
01.03.2019 22:00:00.000 GMT-0000   NaN   NaN  NaN    NaN

[367 rows x 4 columns]